Created helper code file
ContextLab/narrative_complexity pull request #22
Opened 2019-08-11 22:05 UTC by jeroenvanbaar

helpers.py now contains functions from downloader.py and segment_transcripts.py
Paxton: some of these functions had default arguments that were unknown variables; I removed these defaults but feel free to add values back in

2019-08-11 22:09 UTC, jeremymanning requested changes
can you please restore code/downloader.py and also move the notebooks back to code instead of code/notebooks?  then i think it's ready to merge1

2019-08-11 22:09 UTC, jeremymanning commented
note: you can just push your changes to your local fork and the pull request will update automatically (no need to close the request)

2019-08-12 01:06 UTC, jeroenvanbaar commented
The helpers file now contains all downloader code, so no need for that file anymore right?

2019-08-13 03:37 UTC, jeremymanning commented
This can't be merged automatically... Looks like there's a merge conflict.  @jeroenvanbaar can you resolve it on your own?  Happy to help if needed.

2019-08-13 04:02 UTC, jeroenvanbaar commented
Didn’t have time today but will fix this tomorrow, might need your help @jeremymanning

2019-08-13 14:02 UTC, paxtonfitzpatrick requested changes
hey @jeroenvanbaar, thanks for this! I requested two changes that'll make the functions work correctly, and also had one question.  After those changes and @jeremymanning's requests, this will be a super helpful file to have for running code on the cluster, so thank you!!

2019-08-13 14:02 UTC, paxtonfitzpatrick commented on code/helpers.py
> +def get_windows(transcript, wsize):
can you add `wsize=50` as default?

2019-08-13 14:02 UTC, paxtonfitzpatrick commented on code/helpers.py
> +def topic_model(transcript, vec_params, sem_params, return_windows=False):
can you add `vec_params=None` and `sem_params=None` as default, and then add this code just before the `traj = fit_transform(...` line?
```
if not vec_params:
    vec_params = {
        'model' : 'CountVectorizer', 
        'params' : {
            'stop_words' : sw.words('english')
        }
    }

if not sem_params:
    sem_params = {
        'model' : 'LatentDirichletAllocation', 
        'params' : {
            'n_components' : 100,
            'learning_method' : 'batch',
            'random_state' : 0,
        }
    }
```

2019-08-13 14:02 UTC, paxtonfitzpatrick commented on code/helpers.py
> +def wipe_acting_instructions_from_dialogue(line):
can you describe (maybe add comments to code) what this function does?  I ran it on a sample script and the only difference I could see was that it removes text in parentheses, though I didn't look super closely.

2019-08-13 19:00 UTC, merged